# pytorch_lightning==1.7.7
seed_everything: 42
trainer:
  logger: true
  enable_checkpointing: true
  callbacks: null
  default_root_dir: ../workdirs
  gradient_clip_val: null
  gradient_clip_algorithm: null
  num_nodes: 1
  num_processes: null
  devices: null
  gpus: 1
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 140
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  log_every_n_steps: 50
  accelerator: null
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: null
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
pipeline: test
exp_name: sice
version: null
checkpoint: null
model:
  class_path: framework.PSENet
  init_args:
    tv_w: 5
    gamma_lower: -2
    gamma_upper: 3
    number_refs: 1
    lr: 5e-4
    afifi_evaluation: false
data:
  class_path: data.LOLDataModule
  init_args:
    data_root: /home/ubuntu/WACV/PSENet-Image-Enhancement/data_root/lol/
    num_workers: 4
